apiVersion: v1
kind: Service
metadata:
  name: kubernetes-resource-service
  namespace: poseidon1-dev
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
