apiVersion: v1
kind: Service
metadata:
  name: kustomize-service-test2
  namespace: poseidon1-dev
spec:
  selector:
    app: my-app-appset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
