site_name: OpenShift
site_url: https://sopra-steria-norge-kubernetes.github.io/OpenShift/
repo_url: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git
repo_name: Sopra Steria - OpenShift
edit_uri: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift/blob/main/docs/
nav: 
  - Get started: index.md
  - About Container Platform as a Service: 
    - Introduction: About Container-Platform-as-a-Service/introduction.md
    - Service breakdown: About Container-Platform-as-a-Service/Service-breakdown.md
    - OpenShift tenants: About Container-Platform-as-a-Service/openshift-tenants.md
    - Roles and responsibilities: About Container-Platform-as-a-Service/roles-and-responsibilities.md
    - Managing tenant configuration: About Container-Platform-as-a-Service/managing-tenant-configuration.md
    - Developing Container Platform as a Service: About Container-Platform-as-a-Service/developing-container-platforma-as-a-service.md
  - OpenShift Tenants: 
    - Introduction: OpenShift Tenants/Introduction-to-openshift-tenants.md
    - Quick start: OpenShift Tenants/Orderopenshift-tenant-quick-start-guide.md
    - Order OpenShift tenant: OpenShift Tenants/Order-openshift-tenant.md
    - Install Kubeseal: OpenShift Tenants/install-kubeseal.md
    - Authentication Methods for ArgoCD with GitHub: 
      - Authenticate with Personal Access Token (PAT): OpenShift Tenants/Authentication Methods for ArgoCD with GitHub/authenticate-with-personal-access-token.md
      - Authenticate with GitHub App: OpenShift Tenants/Authentication Methods for ArgoCD with GitHub/authenticate-with-github-app.md
      - Authenticate with SSH: OpenShift Tenants/Authentication Methods for ArgoCD with GitHub/authenticate-with-ssh.md
  - CI/CD:
    - Introduction: CI-CD/gitops-introduction.md
    - CI/CD with Tekton Pipelines: CI-CD/continuous-integration-and-delivery-with-tekton-pipelines.md
  - Secret Managment:
    - Creating and managing secrets: Secret Managment/creating-and-managing-openshift-secrets.md
    - Encrypt secrets: Secret Managment/encrypting-secret-with-kubeseal.md
    - Configure external secrets: Secret Managment/configuring-external-secrets.md
  - Observability:
    - Introduction: Observability/Introduction.md
    - Using OpenShift observability: Observability/using-openshift-observability.md
    #- Using network observability: Observability/using-network-observability.md
    - Configure monitoring for a tenant: Observability/configuring-monitoring-for-a-tenant.md
    - Configure Grafana and Thanos: Observability/configure-grafana-and-thanos-query.md
  - Monitoring:
    - Slack integration with OpenShift alerts: Monitoring/slack-integration-with-openshift-alerts.md
  - Network:
    - Introduction: Network/introduction.md
    - Connect application cross namespaces: Network/connect-openshift-application-cross-namespaces.md
    - Exposing an OpenShift Service: Network/exposing-an-openshift-service.md
  - Storage:
    - OpenShift Storage: Storage/openshift-storage.md
  - Security:
    - Advanced Cluster Security (ACS): Security/advanced-cluster-security.md


markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - search

theme:
  name: material
  logo: assets/Sopra_Steria_logo.svg.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/eye

  features:
    - navigation.instant
    - navigation.path
    - content.code.copy
    - navigation.footer
    - content.action.edit
    
  font:
    code: Roboto Mono
    text: Roboto

  palette: 
    primary: white
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: white
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   primary: white
    #   scheme: default 
    #   toggle:
    #     icon: fontawesome/solid/toggle-off
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   primary: white
    #   scheme: slate
    #   toggle:
    #     icon: fontawesome/solid/toggle-on
    #     name: Switch to system preference

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - Team Poseidon
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git

