site_name: Container Platform as a Service
site_url: https://sopra-steria-norge-kubernetes.github.io/OpenShift/
repo_url: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git
repo_name: Sopra Steria - OpenShift
edit_uri: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift/blob/main/docs/

nav: 
  #- Get started: index.md
  - Home: 
    - Introduction: About Container-Platform-as-a-Service/introduction.md
    - Service Breakdown: 
      - CPaaS: About Container-Platform-as-a-Service/Service Breakdown/Service-breakdown.md
      - Core Concepts: About Container-Platform-as-a-Service/Service Breakdown/core-concepts.md
      - Secret Management:
        - Creating and managing secrets: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/creating-and-managing-openshift-secrets.md
        - External Secrets:
          - Introduction: About Container-Platform-as-a-Service/Service Breakdown/Secret Management//External Secrets/Introduction.md
          - Creating secret store: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/External Secrets/configuration-secretstore.md
          - Creating external secrets: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/External Secrets/creating-external-secrets.md
          - Creating Cluster External Secret: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/External Secrets/cluster-external-secrets.md
        - Sealed Secrets:
          - Introduction: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/Sealed Secrets/Introduction.md
          - Encrypt secrets with SealedSecrets: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/Sealed Secrets/encrypting-secret-with-sealed-secrets.md
          - Install Kubeseal: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/Sealed Secrets/install-kubeseal.md
      - GitOps:
        - Introduction to GitOps on OpenShift: About Container-Platform-as-a-Service/Service Breakdown/GitOps/Introduction-GitOps.md
        - GitOps Setup: About Container-Platform-as-a-Service/Service Breakdown/GitOps/gitops-setup.md
        - OpenShift GitOps Best Practices: About Container-Platform-as-a-Service/Service Breakdown/GitOps/gitops-best-practices.md
        - GitOps - Authentication Methods:
          - Authenticate with Personal Access Token (PAT): About Container-Platform-as-a-Service/Service Breakdown/GitOps/Authentication Methods/authenticate-with-personal-access-token.md
          - Authenticate with GitHub App: About Container-Platform-as-a-Service/Service Breakdown/GitOps/Authentication Methods/authenticate-with-github-app.md
          - Authenticate with SSH: About Container-Platform-as-a-Service/Service Breakdown/GitOps/Authentication Methods/authenticate-with-ssh.md
        - Private Helm Registry:
          - Introduction: About Container-Platform-as-a-Service/Service Breakdown/GitOps/Private Helm Registry/introduction.md
          - Azure Configuration: About Container-Platform-as-a-Service/Service Breakdown/GitOps/Private Helm Registry/private-helm-registry-azure.md
          - Using a Private Helm Registry: About Container-Platform-as-a-Service/Service Breakdown/GitOps/Private Helm Registry/private-helm-reg-usage.md
        - Auto-merging for Teams & Tenants: About Container-Platform-as-a-Service/Service Breakdown/GitOps/auto-merging.md
        - Custom auto-defined targetRevision: About Container-Platform-as-a-Service/Service Breakdown/GitOps/cutom-auto-defined-target-revision.md
        - Multiple Values Files: About Container-Platform-as-a-Service/Service Breakdown/GitOps/multiple-values-files.md
      - Observability:
        - Introduction: About Container-Platform-as-a-Service/Service Breakdown/Observability/Introduction.md
        - Using OpenShift Observability: About Container-Platform-as-a-Service/Service Breakdown/Observability/using-openshift-observability.md
        # - Monitoring & Logging:
        #   - Configure Monitoring for a Tenant: About Container-Platform-as-a-Service/Service Breakdown/Observability/configuring-monitoring-for-a-tenant.md
        - Configure Grafana and Thanos: About Container-Platform-as-a-Service/Service Breakdown/Observability/configure-grafana-and-thanos-query.md
        - Slack integration with OpenShift alerts: About Container-Platform-as-a-Service/Service Breakdown/Observability/slack-integration-with-openshift-alerts.md
        # - Grafana: About Container-Platform-as-a-Service/Service Breakdown/Observability/grafana.md
        # - Alert Forwarding: About Container-Platform-as-a-Service/Service Breakdown/Observability/alert-forwarding.md
      - Network:
        - Introduction: About Container-Platform-as-a-Service/Service Breakdown/Network/introduction.md
        - Connect application cross namespaces: About Container-Platform-as-a-Service/Service Breakdown/Network/connect-openshift-application-cross-namespaces.md
        - Exposing an OpenShift Service: About Container-Platform-as-a-Service/Service Breakdown/Network/exposing-an-openshift-service.md
        - Add an external IP with MetalLB: About Container-Platform-as-a-Service/Service Breakdown/Network/External-IP-with-MetalLB.md
        - How to use EgressIP: About Container-Platform-as-a-Service/Service Breakdown/Network/How-to-use-EgressIP.md
        - Egress Firewall: About Container-Platform-as-a-Service/Service Breakdown/Network/egress-firewall.md
      - Security:
        - Advanced Cluster Security (ACS): About Container-Platform-as-a-Service/Service Breakdown/Security/advanced-cluster-security.md
      - Resource Management:
        - Resource Management: About Container-Platform-as-a-Service/Service Breakdown/Resource Management/resource-management.md
        - Team Resource Dashboards: About Container-Platform-as-a-Service/Service Breakdown/Resource Management/team-resource-dashboards.md
      - Role Based Access Control: 
        - RBAC: About Container-Platform-as-a-Service/Service Breakdown/RBAC/rbac.md
      - Storage:
        - OpenShift Storage: About Container-Platform-as-a-Service/Service Breakdown/Storage/openshift-storage.md
      - Backup:
        - Backup Persistent Volumes using VolumeSnapshots: About Container-Platform-as-a-Service/Service Breakdown/Backup/backup-persistent-volumes-using-volumesnapshots.md
        - Backup process for tenants using Velero: About Container-Platform-as-a-Service/Service Breakdown/Backup/backup-process-for-tenants-using-velero.md
    # - Roles and responsibilities: About Container-Platform-as-a-Service/roles-and-responsibilities.md
    # - OpenShift tenants: About Container-Platform-as-a-Service/openshift-tenants.md
    # - Managing tenant configuration: About Container-Platform-as-a-Service/managing-tenant-configuration.md
    # - Developing Container Platform as a Service: About Container-Platform-as-a-Service/developing-container-platforma-as-a-service.md
  - Quick Start:
    - OpenShift Teams: Quick Start/teams-quick-start.md
    - OpenShift Tenants: Quick Start/tenants-quick-start.md
  - OpenShift Teams Features:
    - Team: OpenShift Teams/Team features/team.md
    - Resource Management: OpenShift Teams/Team features/resource-management.md
    - RBAC: OpenShift Teams/Team features/rbac.md
    - Observability: 
      - Introduction: OpenShift Teams/Team features/observability/observability.md
      - Examples: OpenShift Teams/Team features/observability/examples.md
      - Stack Sizing: OpenShift Teams/Team features/observability/monitoring-stack-sizing.md
    - Gitops:
      - GitOps Introduction: OpenShift Teams/Team features/gitops/gitops-introduction.md
      - GitOps - Argo CD: OpenShift Teams/Team features/gitops/gitops-argocd.md
      - GitOps - Authentication: OpenShift Teams/Team features/gitops/gitops-authentication.md
    - Secret Management: OpenShift Teams/Team features/secret-management.md
  - OpenShift Tenants Features: 
    - Namespace: OpenShift Tenants/Tenant features/namespace.md
    - Environment: OpenShift Tenants/Tenant features/environments.md
    - Network Policy: OpenShift Tenants/Tenant features/networkpolicy.md
    - Role Based Access Control: OpenShift Tenants/Tenant features/rbac.md
    - Monitoring: OpenShift Tenants/Tenant features/configuring-monitoring-for-a-tenant.md
    - GitOps: 
      - GitOps & ArgoCD Introduction: OpenShift Tenants/Tenant features/GitOps/gitops-introduction.md
      - GitOps - Argo CD: OpenShift Tenants/Tenant features/GitOps/gitops-argocd.md
      - GitOps - Authentication: OpenShift Tenants/Tenant features/GitOps/gitops-authentication.md
      - GitOps - Private Helm Registry: OpenShift Tenants/Tenant features/GitOps/private-helm-registry-openshift-tenant.md
    - Backup: OpenShift Tenants/Tenant features/backup.md
    - Secret Managment: OpenShift Tenants/Tenant features/secret-management.md
    - Image Pull Secret: OpenShift Tenants/Tenant features/image-pull-secret.md
    - Slack Alert Integration: OpenShift Tenants/Tenant features/slack-alert-integration.md
    - Team: OpenShift Tenants/Tenant features/team.md
  - Additional Documentation:
    - OpenShift Pipelines:
      - OpenShift Pipelines with Tekton: Additional Documentation/OpenShift Pipelines/OpenShift-pipelines.md
    - OpenShift Serverless:
      - Introduction: Additional Documentation/OpenShift Serverless/Introduction.md
      - Building an OpenShift Serverless image: Additional Documentation/OpenShift Serverless/Building-an-OpenShift-Serverless-Image.md
      - Quick Guide:
        - With tenant configuration: Additional Documentation/OpenShift Serverless/quick-start-guide-with-tenant-chart.md
        - Without tenant configuration: Additional Documentation/OpenShift Serverless/quick-start-guide-without-tenant-chart.md


markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes

plugins:
  - glightbox
  - search

theme:
  name: material
  logo: assets/Sopra_Steria_logo.svg.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/eye

  features:
    - navigation.instant
    - navigation.path
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - content.tooltips
    - search.highlight
    - navigation.top
    - content.footnote.tooltips

  font:
    code: Roboto Mono
    text: Tahoma Mono

  palette: 
    primary: white

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - Team Poseidon
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git

