site_name: Container Platform as a Service
site_url: https://sopra-steria-norge-kubernetes.github.io/OpenShift/
repo_url: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git
repo_name: Sopra Steria - OpenShift
edit_uri: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift/blob/main/docs/

nav: 
  #- Get started: index.md
  - Home: 
    - Introduction: About Container-Platform-as-a-Service/introduction.md
    - Service breakdown: 
      - CPaaS: About Container-Platform-as-a-Service/Service Breakdown/Service-breakdown.md
      - OpenShift Teams: About Container-Platform-as-a-Service/Service Breakdown/openshift-teams.md
      - OpenShift Tenants: About Container-Platform-as-a-Service/Service Breakdown/openshift-tenants.md
      - Secret Management:
        - External Secrets: About Container-Platform-as-a-Service/Service Breakdown/Secret Management/external-secrets.md
      - GitOps:
        - ArgoCD: About Container-Platform-as-a-Service/Service Breakdown/GitOps/argocd.md
      - Observability:
        - Monitoring & Logging: About Container-Platform-as-a-Service/Service Breakdown/Observability/monitoring-and-logging.md
        - Grafana: About Container-Platform-as-a-Service/Service Breakdown/Observability/grafana.md
        - Alert Forwarding: About Container-Platform-as-a-Service/Service Breakdown/Observability/alert-forwarding.md
      - Network: About Container-Platform-as-a-Service/Service Breakdown/network.md
      - Security: About Container-Platform-as-a-Service/Service Breakdown/security.md
      - RBAC: About Container-Platform-as-a-Service/Service Breakdown/rbac.md
      - Storage: About Container-Platform-as-a-Service/Service Breakdown/storage.md
      - Backup: About Container-Platform-as-a-Service/Service Breakdown/backup.md
    # - Roles and responsibilities: About Container-Platform-as-a-Service/roles-and-responsibilities.md
    # - OpenShift tenants: About Container-Platform-as-a-Service/openshift-tenants.md
    # - Managing tenant configuration: About Container-Platform-as-a-Service/managing-tenant-configuration.md
    # - Developing Container Platform as a Service: About Container-Platform-as-a-Service/developing-container-platforma-as-a-service.md
  - Quick Start:
    - OpenShift Teams: Quick Start/teams-quick-start.md
    - OpenShift Tenants: Quick Start/tenants-quick-start.md
  - OpenShift Teams:
    # - Team Introduction: OpenShift Teams/team-introduction.md
    - Team Features:
      - Team: OpenShift Teams/Team features/team.md
      - Resource Management: OpenShift Teams/Team features/resource-management.md
      - RBAC: OpenShift Teams/Team features/rbac.md
      - Observability: OpenShift Teams/Team features/observability/observability.md
      - Gitops:
        - GitOps Introduction: OpenShift Teams/Team features/gitops/gitops-introduction.md
        - GitOps - Argo CD: OpenShift Teams/Team features/gitops/gitops-argocd.md
        - GitOps - Authentication: OpenShift Teams/Team features/gitops/gitops-authentication.md
      - Secret Management: OpenShift Teams/Team features/secret-management.md
  - OpenShift Tenants: 
    # - Introduction: OpenShift Tenants/Introduction-to-openshift-tenants.md
    # - Quick start: OpenShift Tenants/Orderopenshift-tenant-quick-start-guide.md
    # - OpenShift Tenant Template: OpenShift Tenants/OpenShift-tenant-template.md
    - Tenant features:
      - Namespace: OpenShift Tenants/Tenant features/namespace.md
      - Environment: OpenShift Tenants/Tenant features/environments.md
      - Network Policy: OpenShift Tenants/Tenant features/networkpolicy.md
      - Role Based Access Control: OpenShift Tenants/Tenant features/rbac.md
      - GitOps: 
        - Argo CD: OpenShift Tenants/Tenant features/GitOps/argocd.md
        - Auto-merging existing tenants: OpenShift Tenants/Tenant features/GitOps/auto-merge-for-existing-tenants.md
        - Authentication Methods for ArgoCD: 
          - Authenticate with Personal Access Token (PAT): OpenShift Tenants/Tenant features/GitOps/Authentication Methods for ArgoCD/authenticate-with-personal-access-token.md
          - Authenticate with GitHub App: OpenShift Tenants/Tenant features/GitOps/Authentication Methods for ArgoCD/authenticate-with-github-app.md
          - Authenticate with SSH: OpenShift Tenants/Tenant features/GitOps/Authentication Methods for ArgoCD/authenticate-with-ssh.md
        - Private Helm Registry:
          - Introduction: OpenShift Tenants/Tenant features/GitOps/Private Helm Registry/introduction.md
          - Azure Configuration: OpenShift Tenants/Tenant features/GitOps/Private Helm Registry/private-helm-registry-azure.md
          - Openshift Tenant Configuration: OpenShift Tenants/Tenant features/GitOps/Private Helm Registry/private-helm-registry-openshift-tenant.md
          - Using a Private Helm Registry: OpenShift Tenants/Tenant features/GitOps/Private Helm Registry/private-helm-reg-usage.md
      - Backup: OpenShift Tenants/Tenant features/backup.md
      - Secret Managment: OpenShift Tenants/Tenant features/secret-management.md
      - Image Pull Secret: OpenShift Tenants/Tenant features/image-pull-secret.md
      - Slack Alert Integration: OpenShift Tenants/Tenant features/slack-alert-integration.md
      - Team: OpenShift Tenants/Tenant features/team.md
  - Additional Documentation:
    - Monitoring:
      - Slack integration with OpenShift alerts: Additional Documentation/Monitoring/slack-integration-with-openshift-alerts.md
    - Network:
      - Introduction: Additional Documentation/Network/introduction.md
      - Connect application cross namespaces: Additional Documentation/Network/connect-openshift-application-cross-namespaces.md
      - Exposing an OpenShift Service: Additional Documentation/Network/exposing-an-openshift-service.md
      - Add an external IP with MetalLB: Additional Documentation/Network/External-IP-with-MetalLB.md
      - How to use EgressIP: Additional Documentation/Network/How-to-use-EgressIP.md
      - Egress Firewall: Additional Documentation/Network/egress-firewall.md
    - Observability:
      - Introduction: Additional Documentation/Observability/Introduction.md
      - Using OpenShift observability: Additional Documentation/Observability/using-openshift-observability.md
      #- Using network observability: Observability/using-network-observability.md
      - Configure monitoring for a tenant: Additional Documentation/Observability/configuring-monitoring-for-a-tenant.md
      - Configure Grafana and Thanos: Additional Documentation/Observability/configure-grafana-and-thanos-query.md
    - OpenShift GitOps:
      - Introduction to GitOps on OpenShift: Additional Documentation/OpenShift GitOps/Introduction-GitOps.md
      - GitOps Setup: Additional Documentation/OpenShift GitOps/gitops-setup.md
      - OpenShift GitOps Best Practices: Additional Documentation/OpenShift GitOps/gitops-best-practices.md
      - Custom auto-defined targetRevision: Additional Documentation/OpenShift GitOps/cutom-auto-defined-target-revision.md
      - Multiple Values Files: Additional Documentation/OpenShift GitOps/multiple-values-files.md
    - OpenShift Pipelines:
      - OpenShift Pipelines with Tekton: Additional Documentation/OpenShift Pipelines/OpenShift-pipelines.md
    - OpenShift Serverless:
      - Introduction: Additional Documentation/OpenShift Serverless/Introduction.md
      - Building an OpenShift Serverless image: Additional Documentation/OpenShift Serverless/Building-an-OpenShift-Serverless-Image.md
      - Quick Guide:
        - With tenant configuration: Additional Documentation/OpenShift Serverless/quick-start-guide-with-tenant-chart.md
        - Without tenant configuration: Additional Documentation/OpenShift Serverless/quick-start-guide-without-tenant-chart.md
    - Resource Management:
      - Resource Management: Additional Documentation/Resource Management/resource-management.md
      - Team Resource Dashboards: Additional Documentation/Resource Management/team-resource-dashboards.md
    - Secret Managment:
      - Creating and managing secrets: Additional Documentation/Secret Managment/creating-and-managing-openshift-secrets.md
      - External Secrets:
        - Introduction: Additional Documentation/Secret Managment/External Secrets/Introduction.md
        - Creating secret store: Additional Documentation/Secret Managment/External Secrets/configuration-secretstore.md
        - Creating external secrets: Additional Documentation/Secret Managment/External Secrets/creating-external-secrets.md
        - Creating Cluster External Secret: Additional Documentation/Secret Managment/External Secrets/cluster-external-secrets.md
      - Sealed Secrets:
        - Introduction: Additional Documentation/Secret Managment/Sealed Secrets/Introduction.md
        - Encrypt secrets with SealedSecrets: Additional Documentation/Secret Managment/Sealed Secrets/encrypting-secret-with-sealed-secrets.md
    - Security:
      - Advanced Cluster Security (ACS): Additional Documentation/Security/advanced-cluster-security.md
    - Storage:
      - OpenShift Storage: Additional Documentation/Storage/openshift-storage.md
      - Backup:
        - Backup Persistent Volumes using VolumeSnapshots: Additional Documentation/Storage/Backup/backup-persistent-volumes-using-volumesnapshots.md
        - Backup process for tenants using Velero: Additional Documentation/Storage/Backup/backup-process-for-tenants-using-velero.md
    - Tools:
      - Install Kubeseal: Additional Documentation/Tools/install-kubeseal.md


markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes

plugins:
  - glightbox
  - search

theme:
  name: material
  logo: assets/Sopra_Steria_logo.svg.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/eye

  features:
    - navigation.instant
    - navigation.path
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - content.tooltips
    - search.highlight
    - navigation.top
    - content.footnote.tooltips

  font:
    code: Roboto Mono
    text: Tahoma Mono

  palette: 
    primary: white

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - Team Poseidon
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git

