site_name: OpenShift
site_url: https://sopra-steria-norge-kubernetes.github.io/OpenShift/
repo_url: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git
repo_name: Sopra Steria - OpenShift
edit_uri: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift/blob/main/docs/
nav: 
  #- Get started: index.md
  - Container Platform as a Service: 
    - Introduction: About Container-Platform-as-a-Service/introduction.md
    - Service breakdown: About Container-Platform-as-a-Service/Service-breakdown.md
    - OpenShift tenants: About Container-Platform-as-a-Service/openshift-tenants.md
    - Roles and responsibilities: About Container-Platform-as-a-Service/roles-and-responsibilities.md
    - Managing tenant configuration: About Container-Platform-as-a-Service/managing-tenant-configuration.md
    - Developing Container Platform as a Service: About Container-Platform-as-a-Service/developing-container-platforma-as-a-service.md
  - OpenShift Tenants: 
    - Introduction: OpenShift Tenants/Introduction-to-openshift-tenants.md
    - Quick start: OpenShift Tenants/Orderopenshift-tenant-quick-start-guide.md
    - OpenShift Tenant Template: OpenShift Tenants/OpenShift-tenant-template.md
    - Tenant features:
      - Namespace: OpenShift Tenants/Tenant features/namespace.md
      - Environment: OpenShift Tenants/Tenant features/environments.md
      - Network Policy: OpenShift Tenants/Tenant features/networkpolicy.md
      - Role Based Access Control: OpenShift Tenants/Tenant features/rbac.md
      - GitOps: 
        - Argo CD: OpenShift Tenants/Tenant features/GitOps/argocd.md
        - Auto-merging existing tenants: OpenShift Tenants/Tenant features/GitOps/auto-merge-for-existing-tenants.md
        - Authentication Methods for ArgoCD: 
          - Authenticate with Personal Access Token (PAT): OpenShift Tenants/Tenant features/GitOps/Authentication Methods for ArgoCD/authenticate-with-personal-access-token.md
          - Authenticate with GitHub App: OpenShift Tenants/Tenant features/GitOps/Authentication Methods for ArgoCD/authenticate-with-github-app.md
          - Authenticate with SSH: OpenShift Tenants/Tenant features/GitOps/Authentication Methods for ArgoCD/authenticate-with-ssh.md
        - Private Helm Registry:
          - Introduction: OpenShift Tenants/Tenant features/GitOps/Private Helm Registry/introduction.md
          - Setting Up a Private Helm Registry with Argo CD: OpenShift Tenants/Tenant features/GitOps/Private Helm Registry/private-helm-registry-setup.md
      - Backup: OpenShift Tenants/Tenant features/backup.md
      - External Secret: OpenShift Tenants/Tenant features/external-secrets.md
      - Slack Alert Integration: OpenShift Tenants/Tenant features/slack-alert-integration.md
      - Team: OpenShift Tenants/Tenant features/team.md
    - Tenant team:
      - Team-introduction: OpenShift Tenants/Tenant team/team-introduction.md 
  - OpenShift GitOps:
    - Introduction to GitOps on OpenShift: OpenShift GitOps/Introduction-GitOps.md
    - GitOps Setup: OpenShift GitOps/gitops-setup.md
    - OpenShift GitOps Best Practices: OpenShift GitOps/gitops-best-practices.md
    - Custom auto-defined targetRevision: OpenShift GitOps/cutom-auto-defined-target-revision.md
  - OpenShift Pipelines:
     - OpenShift Pipelines with Tekton: OpenShift Pipelines/OpenShift-pipelines.md
  - Secret Managment:
    - Creating and managing secrets: Secret Managment/creating-and-managing-openshift-secrets.md
    - Encrypt secrets: Secret Managment/encrypting-secret-with-kubeseal.md
    - Configure external secrets: Secret Managment/configuring-external-secrets.md
  - Observability:
    - Introduction: Observability/Introduction.md
    - Using OpenShift observability: Observability/using-openshift-observability.md
    #- Using network observability: Observability/using-network-observability.md
    - Configure monitoring for a tenant: Observability/configuring-monitoring-for-a-tenant.md
    - Configure Grafana and Thanos: Observability/configure-grafana-and-thanos-query.md
  - Monitoring:
    - Slack integration with OpenShift alerts: Monitoring/slack-integration-with-openshift-alerts.md
  - Network:
    - Introduction: Network/introduction.md
    - Connect application cross namespaces: Network/connect-openshift-application-cross-namespaces.md
    - Exposing an OpenShift Service: Network/exposing-an-openshift-service.md
    - Add an external IP with MetalLB: Network/External-IP-with-MetalLB.md
    - How to use EgressIP: Network/How-to-use-EgressIP.md
  - Storage:
    - OpenShift Storage: Storage/openshift-storage.md
    - Backup:
      - Backup Persistent Volumes using VolumeSnapshots: Storage/Backup/backup-persistent-volumes-using-volumesnapshots.md
      - Backup process for tenants using Velero: Storage/Backup/backup-process-for-tenants-using-velero.md
  - Security:
    - Advanced Cluster Security (ACS): Security/advanced-cluster-security.md
  - OpenShift Serverless:
    - OpenShift Serverless/Introduction.md
    - OpenShift Serverless/Building-an-OpenShift-Serverless-Image.md
    - Quick Guide:
      - OpenShift Serverless/quick-start-guide-with-tenant-chart.md
      - OpenShift Serverless/quick-start-guide-without-tenant-chart.md
  - Tools:
    - Install Kubeseal: Tools/install-kubeseal.md


markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes

plugins:
  - glightbox
  - search

theme:
  name: material
  logo: assets/Sopra_Steria_logo.svg.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/eye

  features:
    - navigation.instant
    - navigation.path
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - content.tooltips
    - search.highlight
    - navigation.top
    - content.footnote.tooltips

  font:
    code: Roboto Mono
    text: Tahoma Mono

  palette: 
    primary: white

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - Team Poseidon
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Sopra-Steria-Norge-Kubernetes/OpenShift.git

