apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Referencing a public repo outside the main repository

helmCharts:
  - name: helm-test
    repo: https://teamposeidonocp.github.io/helm-test-repo/
    version: 0.0.1
    releaseName: helm-test
    namespace: poseidon1-dev
    valuesFile: values.yaml
