apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poseidon2-dev-helm-example-user-defined
  namespace: gitops-developers # REMEMBER TO USE THE APPROPRIATE NAMESPACE HERE
spec:
  project: poseidon1
  source:
    chart: helm-test
    repoURL: https://teamposeidonocp.github.io/helm-test-repo/
    targetRevision: 0.0.1
    helm:
      releaseName: helm-test
  destination:
    server: "https://kubernetes.default.svc"
    namespace: poseidon1-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  