---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-appset
  template:
    metadata:
      labels:
        app: my-app-appset
    spec:
      containers:
        - name: my-container-appset
          image: busybox
          command: ["sleep", "3600"]
          ports:
          - containerPort: 80
          resources:             # Add resource requests and limits
            limits:
              memory: "64Mi"
              cpu: "100m"
