apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Referencing a public repo outside the main repository

helmCharts:
  - name: helm-testing
    repo: oci://poseidon1.azurecr.io
    version: 1.0.1
    releaseName: nginx-helm-test
    namespace: poseidon1-dev
    valuesFile: values.yaml